/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n3.0.1-2-g91af06e-QtAV"
#endif /* AVUTIL_FFVERSION_H */
